// This is header for Main Control Panel
// MainPanel was also generated by QT Designer and saved as UI file

#ifndef __MainPanel_H
#define __MainPanel_H

#include "ui_MainPanel.h"

#include <string>
#include <QMainWindow>

class MainPanel : public QDockWidget, private Ui::MainPanel
{
	Q_OBJECT

public:
	MainPanel( QWidget* parent = 0);
	~MainPanel();

	
 public slots:
    // Here we can add all triggering functions from varios QT widgets (Thiha)
	// Triggering function should be created and defined in QT Designer
    // and they can be called from here as SLOTs

private:

	// pointer to the main window (Optional)
	QMainWindow* m_pMainWindow;

};

#endif
