#include "FindContoursPlugin.h"
#include "FilterContoursPlugin.h"
#include "EditContoursPlugin.h"
#include "ImproveContoursPlugin.h"
#include "SubtractBackgroundPlugin.h"
#include "SmoothPlugin.h"
#include "TrackContoursPlugin.h"
#include "LKContoursPlugin.h"
#include "CamShiftPlugin.h"
#include "MatchTemplatePlugin.h"

#include "CombinedTrackingPlugin.h"
#include "FindFeaturesPlugin.h"
#include "NormalizeContoursPlugin.h"
#include "CropPlugin.h"
#include "ResizeMoviePlugin.h"
